### ISSUE TITLE
sh: host: command not found

### ISSUE THREAD

**Issue by nguyendeicide** [holodyn/dyndns-htaccess#1]
I found this issue via cronjob:
sh: host: command not found
Is there any problem?

**Comment by dakuzen** [comment]
Sounds like you need to check your environment for the command - it may not exist or be available to your user.

http://www.cyberciti.biz/faq/linux-unix-host-command-examples-usage-syntax/
http://webplay.pro/linux/centos/how-to-install-dig-host-and-nslookup-bind-utils-on-centos.html

**Comment by holodyn** [comment]
the gethostbyname() method has been added
