### ISSUE TITLE
htaccess error "no comments are allowed here"

### ISSUE THREAD

**Issue by DGEAPerez** [holodyn/dyndns-htaccess#2]
Hi!.. thanks for this piece of cod.. It rocks!... 

But in my environment (CentOS 6.5) it is not allowed a comment inline after a command, so I edited the script in this way to fix it...

Original line 63
$outputRows[] = 'Allow from ' . $host_ip . ' # ' . $host_result;

to 
$outputRows[] = '# ' . $host_result; // Comment splited from command
$outputRows[] = 'Allow from ' . $host_ip; // Command to allow ip
if (!feof($fh))
   $line = fgets($fh); // A line was added to the original code, so the next must be ignored

With this simple modification the script runs like a charm...

Another approach is just edit line 63 to this:
$outputRows[] = 'Allow from ' . $host_ip;

Because I think is very clear after DYNDNS declaration, the following is the IP detected...

Thank you!

Regards...

E.

**Comment by dakuzen** [comment]
Thanks for the contribution!

I've removed the trailing comment.  It seems cleaner to just remove it vs risking an unrelated trailing line being deleted because we're assuming it to be the host comment.

**Comment by DGEAPerez** [comment]
Glad to help!...
About to remove the comment, it was my "solution" but I preffered to let you take the best approach :)

Regards...

E.
